### ISSUE TITLE
Lottery command feature

### ISSUE THREAD

**Issue by LeSirH** [TheTypingMatch/lecashbot#17]
This is a feature I plan on adding in `v2.0.0` of LeCashBot.

- `$lottery` - View lottery information
    - Prize pool
    - Entry cost
    - When the lottery ends/started
    - How to enter
- `$lottery enter` - Enter the lottery
    - Warns the user if they do not have enough to enter
    - Replying message confirming how much has been spent

These lotteries may last on a weekly interval with a $100, $1,000, or $10,000 entry fee.

**Comment by TheProdigyHenry** [comment]
A weekly interval may be a bit too long. Perhaps a daily/12-hour interval might be better. Or, perhaps several different types of lotteries going on at the same time.

**Comment by Le-SirH** [comment]
That might be a good idea. Maybe something like this:
| Lottery | Entry Fee |
|---|---|
| Daily | $100 |
| Weekly | $1,000 |
| Monthly | $10,000 |

**Comment by LeSirH** [comment]
Idea: There could also be a lottery leaderboard to view biggest winners.
