### ISSUE TITLE
Leaderboard command: faster sorting algorithm.

### ISSUE THREAD

**Issue by LeSirH** [TheTypingMatch/lecashbot#36]
As more users sign up for the bot, it takes longer and longer for the bot to respond with a sorted leaderboard.

**Comment by Le-SirH** [comment]
This could either be solved by a faster algorithm, a pre-sorted leaderboard that is updated frequently, or both.

**Comment by DamienVesper** [comment]
Use a single-step algorithm to sort the leaderboard.

**Comment by Le-SirH** [comment]
How does a single-step algorithm work?

**Comment by DamienVesper** [comment]
One-line sorter.

**Comment by LeSirH** [comment]
Here is a work in progress on this issue: fff2243.

**Comment by DamienVesper** [comment]
Takes an average of 3 to 4 seconds for the leaderboard to sort. There's still some improvement, but it can also be caused by typing status overhead + TypeScript limitations.

**Comment by LeSirH** [comment]
> Takes an average of 3 to 4 seconds for the leaderboard to sort. There's still some improvement, but it can also be caused by typing status overhead + TypeScript limitations.

That is the time it takes before the fix. Now, it only takes about 0.25 seconds including the Discord API & database latency.
