### ISSUE TITLE
$daily upvote

### ISSUE THREAD

**Issue by DarkMagicianGirl9900** [TheTypingMatch/lecashbot#58]
**Is your feature request related to a problem? Please describe.**
Right we can just do `$daily` to collect free NT cash without having to actually do anything to give anything back to the bot or show any support. Members gain money while the bot is losing money. It's a win-lose situation. It's kinda not fair.

**Describe the solution you'd like**
A win-win situation for both parties.

**Describe alternatives you've considered**
Add a requirement to collect `$daily`. They need to upvote the bot first in order to claim their dailies. This is a thing for many other popular bots too. Like with some pokemon bot and waifu bot and RPG bot, you can't collect your daily unless you upvote them.

**Additional context**
All these are just different ideas
Image 1 : Maybe add the upvote link to `$donate` or `$help`
![1](https://user-images.githubusercontent.com/52117760/88368446-f2026400-cd42-11ea-8288-eeba1de5692d.png)

Image 2 : Or add it in the footnote
![2](https://user-images.githubusercontent.com/52117760/88368455-fa5a9f00-cd42-11ea-89bc-5113684ebce3.png)

And then the following two choices:
Message appears when you try to do `$daily`

Image 3 : Get nothing at all unless they vote
![3](https://user-images.githubusercontent.com/52117760/88368484-08102480-cd43-11ea-9e13-2878e188c0a6.png)

Image 4 : Still get their daily streak even if they don't vote, just without the upvote bonuses 
![4](https://user-images.githubusercontent.com/52117760/88368496-0d6d6f00-cd43-11ea-9d2f-91f10f4f42d5.png)

~~Never Gonna Give You Up~~

**Comment by Le-SirH** [comment]
We can make this voting a requirement.

**Comment by Le-SirH** [comment]
![image](https://user-images.githubusercontent.com/46948579/91416350-7d708880-e80c-11ea-98e9-9863f1f56ed5.png)

**Comment by GoodGradesBoy** [comment]
top.gg api being garbage so please no make requirement and make it boost thank
