### ISSUE TITLE
[FEAT] Show if the user has already been entered in the lottery command.

### ISSUE THREAD

**Issue by ryan-harrington** [TheTypingMatch/lecashbot#74]
## Example
Ends in: `1:21:49:57`
Entries: **12**
**Entered: yes**
Entry Fee: $**1,000**
Prize Pool: $**12,000**

**Comment by GoodGradesBoy** [comment]
will do

Entered: **yes**
Entered: **no**


y e s

**Comment by GoodGradesBoy** [comment]
a ternarye y tearnary terary terany operator can be used to determine this
````js
lottery.entries.includes(message.author.id)
```

**Comment by GoodGradesBoy** [comment]
close sesame
