### ISSUE TITLE
[Feature request]  Guess that Sticker Game

### ISSUE THREAD

**Issue by GoodGradesBoy** [TheTypingMatch/lecashbot#80]
**Is your feature request related to a problem? Please describe.**
we forget sticker names all the time in Nitro Type. so why not make ourselves look more stupid by trying to guess sticker names.

**Describe the solution you'd like**
have the bot post a sticker, give the user 7 seconds to respond to answer. user can also bet money which is doubled when winning.

**Describe alternatives you've considered**
use bootstrap to auto update stickers

**Additional context**
lesirh kinda sexy though

**Comment by DamienVesper** [comment]
Not enough variety to put a reasonable monetary value on it.
